// // ------------------------------------------------------------------------------
// // <auto-generated>
// //    Generated by avrogen, version 1.11.1
// //    Changes to this file may cause incorrect behavior and will be lost if code
// //    is regenerated
// // </auto-generated>
// // ------------------------------------------------------------------------------
// namespace csharp.Model
// {
// 	using System;
// 	using System.Collections.Generic;
// 	using System.Text;
// 	using Avro.Specific;
//
// 	public partial class User : ISpecificRecord
// 	{
// 		public static Avro.Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"Confluent.Kafka.Examples.AvroSpecific" +
// 				"\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"favorite_number\",\"type\":\"lo" +
// 				"ng\"},{\"name\":\"favorite_color\",\"type\":\"string\"}]}");
// 		private string _name;
// 		private long _favorite_number;
// 		private string _favorite_color;
// 		public virtual global::Avro.Schema Schema
// 		{
// 			get
// 			{
// 				return User._SCHEMA;
// 			}
// 		}
// 		public string name
// 		{
// 			get
// 			{
// 				return this._name;
// 			}
// 			set
// 			{
// 				this._name = value;
// 			}
// 		}
// 		public long favorite_number
// 		{
// 			get
// 			{
// 				return this._favorite_number;
// 			}
// 			set
// 			{
// 				this._favorite_number = value;
// 			}
// 		}
// 		public string favorite_color
// 		{
// 			get
// 			{
// 				return this._favorite_color;
// 			}
// 			set
// 			{
// 				this._favorite_color = value;
// 			}
// 		}
// 		public virtual object Get(int fieldPos)
// 		{
// 			switch (fieldPos)
// 			{
// 			case 0: return this.name;
// 			case 1: return this.favorite_number;
// 			case 2: return this.favorite_color;
// 			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
// 			};
// 		}
// 		public virtual void Put(int fieldPos, object fieldValue)
// 		{
// 			switch (fieldPos)
// 			{
// 			case 0: this.name = (System.String)fieldValue; break;
// 			case 1: this.favorite_number = (System.Int64)fieldValue; break;
// 			case 2: this.favorite_color = (System.String)fieldValue; break;
// 			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
// 			};
// 		}
// 	}
// }
public class User
{
    // public Schema Schema
    //     => Schema.Parse(File.ReadAllText("/Users/dave.han/NIH/kafka-schema-registry-demo/producer/csharp/Schema/User.avsc"));
    public string name { get; set; }
    public long favorite_number { get; set; }
    public string favorite_color { get; set; }
}